### ISSUE TITLE
[FEAT] 책 정보 자세히보기 API - 전체 평점 기능 구현

### ISSUE THREAD

**Issue by gogori6565** [Moongeul/Backend#121]
## 🚀 About Issue 🚀

책 정보 자세히보기 페이지의 전체 평점 기능을 구현합니다.

## ✅ Todo 

- [x] REVIEW_ARTICLE, READBOOKS 의 속성 이름 star_rating -> rating 으로 변경
- [x] BOOK TABLE 'rating_average', 'rating_count' attribute 추가
- [x] 새로운 평점 입력 시(책장 평점 입력/수정 시, 감상평 게시글 평점 수정 시), 평균 평점 계산 기능 구현
