### ISSUE TITLE
[FEAT] 처음 접속한 사용자 추가 설정(마케팅 정보 동의 여부, 선호하는 책 취향 태그, 정보 공개 여부) 등록 기능 구현

### ISSUE THREAD

**Issue by rhkr8521** [Moongeul/Backend#18]
## 🚀 About Issue 🚀

처음 접속한 사용자 추가 설정(마케팅 정보 동의 여부, 선호하는 책 취향 태그) 정보를 등록하는 기능을 구현합니다.

## ✅ Todo 

- [x] 마케팅 정보 동의 여부 등록 기능 구현
- [x] 선호하는 책 취향 태그 등록 기능 구현
- [x] 정보 공개 여부 초기 설정
