### ISSUE TITLE
[FEAT] 책장(읽은 책/읽고 싶은 책) 생성, 조회, 수정, 삭제 기능 구현

### ISSUE THREAD

**Issue by gogori6565** [Moongeul/Backend#52]
## 🚀 About Issue 🚀

책장(읽은 책/읽고 싶은 책) 생성, 조회, 수정, 삭제 기능을 구현합니다.

## ✅ Todo 

- [x] 책장 조회 기능(R)
- [x] 책장 등록 기능(C)
- [x] 책장 상세 정보 수정 기능(U)
- [x] 책장 삭제 기능(D)

**Comment by rhkr8521** [comment]
정말 고생하셨습니다!
