### ISSUE TITLE
[FIX] 팔로잉 기능 최적화 및 팔로워 보기 기능 구현

### ISSUE THREAD

**Issue by rhkr8521** [Moongeul/Backend#53]
## 🚀 About Issue 🚀

팔로잉 기능 최적화 및 팔로워 보기 기능을 구현합니다.

## ✅ Todo 

- [x] 전반적인 팔로우 기능 복잡도 체크
- [x] 팔로워 기능 구현
- [x] 캐싱 활성화 ( with Redis)
